
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 29 15:43:48 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VECEJED = 40;
  public static final int PROCENAT = 35;
  public static final int CONST = 23;
  public static final int LOGI = 42;
  public static final int ISTO = 36;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 28;
  public static final int MINUS = 30;
  public static final int RAZLICITO = 37;
  public static final int RPAREN = 7;
  public static final int COMMA = 11;
  public static final int CLASS = 21;
  public static final int INC = 44;
  public static final int DIV = 32;
  public static final int PLUS = 10;
  public static final int IF = 18;
  public static final int THIS = 29;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int NUMBER = 14;
  public static final int DUPTACKA = 46;
  public static final int BREAK = 20;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int TIMES = 31;
  public static final int MANJE = 39;
  public static final int MANJEJED = 41;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int VECE = 38;
  public static final int LOGILI = 43;
  public static final int LSQUARE = 33;
  public static final int ENUM = 22;
  public static final int READ = 27;
  public static final int FINAL = 48;
  public static final int RSQUARE = 34;
  public static final int CHARCONST = 16;
  public static final int WHILE = 25;
  public static final int TACKA = 47;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 17;
  public static final int PROG = 2;
  public static final int HASHTAG = 49;
  public static final int DEC = 45;
  public static final int PRINT = 12;
  public static final int DO = 24;
}

