
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
  // ja dodao kljucne reci
  public static final int BREAK = 18;
  public static final int CLASS = 19;
  public static final int ENUM = 20;
  public static final int CONST = 21;
  public static final int DO = 22;
  public static final int WHILE = 23;
  public static final int NEW = 24;
  public static final int READ = 25;
  public static final int EXTENDS = 26;
  public static final int CONTINUE = 27;
  public static final int THIS = 28;
  public static final int SUPER = 29;
  public static final int GOTO = 30;
  public static final int RECORD = 31;
  
  // const
  public static final int CHARCONST = 32;
  public static final int BOOLCONST = 33;
  
  // operatori 
  public static final int PROCENAT = 34;
  public static final int ISTO = 35;
  public static final int RAZLICITO = 36;
  public static final int VECE = 37;
  public static final int MANJE = 38;
  public static final int VECEJED = 39;
  public static final int MANJEJED = 40;
  public static final int LOGI = 41;
  public static final int LOGILI = 42;
  public static final int INC = 43;
  public static final int DEC = 44;
  public static final int DUPTACKA = 45;
  public static final int TACKA = 46;
  public static final int LSQUARE = 47;
  public static final int RSQUARE = 48;
  public static final int DIV = 49;
  public static final int TIMES = 50;
  public static final int MINUS = 51;
}

